okta:
  oauth2:
    issuer: https://dev-158606.oktapreview.com/oauth2/default
    client-id: 0oafqwenodi6cPzSC0h7
    client-secret: FLuPvd9Gf87Wu17Q6CAAFqK6WaIlPDdcKwQ9XplM

spring:
  profiles:
    active: @spring.profiles.active@