spring:
  profiles:
    active: @spring.profiles.active@
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oafrf327dXcTWh3j0h7
            client-secret: gXoRPO1uKff1X12MZpGIppbsyDDvi6QHFrfqooFU
            scope: openid email profile
        provider:
          okta:
            issuer-uri: https://dev-737523.oktapreview.com/oauth2/default